# Generated by Django 5.2.6 on 2025-09-18 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-F]{8}$', 'ID must be 8 hexadecimal characters')])),
                ('access_level', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='green', max_length=20)),
            ],
        ),
    ]
